### ISSUE TITLE
Migrate from bors to GH merge queue

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#1712]
#1711 will revert us back to bors. Opening this issue to track.

Some local notes on ideas: we could filter the `Edit Steps` yaml file to:
```
 - label: "Skip if not by launch or merge queue."
   if: (build.pull_request.labels includes "Launch Buildkite") || (build.branch =~ /^gh-readonly-queue\/main\//)
   command: "buildkite-agent pipeline upload"
   key: "run_ci"
   agents:
     config: init
     queue: central
   env:
     BUILDKITE_LONGRUNS: "false"
```

Ideally, this first condition would be `build.pull_request.labeled == "Launch Buildkite"`, but the `labeled` attribute is part of the GH `action` (https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#label)

Conversation with buildkite supprt:

```
I was hoping to see if there is a way that users have
access to the variable that triggers the event via label changes.

For example, we have a GitHub label called “launch buildkite”, and
ideally we’d have access to build.pull_request.label_added == “launch buildkite”.
Meaning, this build was a triggered event by adding the label “launch buildkite”.
It seems that buildkite at least knows when labels are added in the pipeline
settings in GutHub integrations.

I don’t see this in the list in the docs, but I was hoping to see if you
could provide me with pointers, thank you!
```
Resonse:
```
The `build.pull_request.labels` will get populated with each new
webhook information we receive, but it will have all the label information
associated with that PR; at the moment we don't have the option to only
set the label(s) that trigger the build..

As you noticed, the information is in the payload we received from GH, so
maybe you can parse it in the environment hook and add it to an environment variable?
```

cc @simonbyrne
