### ISSUE TITLE
Run a perfect model calibration using precipitation and TOA radiative fluxes in the loss function

### ISSUE THREAD

**Issue by nefrathenrici** [CliMA/ClimaAtmos.jl#3142]
This calibration is needed prior to addressing https://github.com/CliMA/ClimaCoupler.jl/issues/726

Target parameters: 
- Precipitation:`precipitation_timescale`
- Radiative fluxes: `ocean_surface_albedo`, maybe `water_refractive_index`

Atmosphere configuration: 
```yaml
dt: "120secs"
t_end: "300days"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
rayleigh_sponge: true
moist: "equil"
precip_model: "0M"
surface_setup: "DefaultMoninObukhov"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
rad: "clearsky"
dt_rad: "6hours"
toml: [toml/longrun_aquaplanet_rhoe_equil_55km_nz63_gray_0M.toml]
override_τ_precip: false
```

Diagnostics: `rlut`, `rsut`, `precip`
